name: flutter_google_places_hoc081098
description: Google places autocomplete widgets for flutter. No wrapper, use https://pub.dartlang.org/packages/google_maps_webservice. Better flutter_google_places, updated by @hoc081098
version: 1.2.0
homepage: https://github.com/hoc081098/flutter_google_places
repository: https://github.com/hoc081098/flutter_google_places
funding:
  - https://www.buymeacoffee.com/hoc081098

environment:
  sdk: '>=2.14.0 <3.0.0'
  flutter: '>=2.8.0'

dependencies:
  flutter:
    sdk: flutter
  google_api_headers: ^1.3.0
  google_maps_webservice:
    path: ./google_maps_webservice-0.0.20-nullsafety.5/
  http: ^0.13.4
  rxdart: ^0.27.4
  rxdart_ext: ^0.2.2
  listenable_stream: ^1.1.0
  collection: ^1.15.0
  flutter_bloc_pattern: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

flutter:
  assets:
    - packages/flutter_google_places_hoc081098/assets/google_black.png
    - packages/flutter_google_places_hoc081098/assets/google_white.png
